[package]
name = "bridge_example"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false }
ink_lang = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { version = "3.0.0-rc3", git = "https://github.com/paritytech/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }

# Only used for dev network
ink_log = { git = "https://github.com/patractlabs/ink-log", branch = "master", default-features = false }
#ink_log = { git = "https://github.com/patractlabs/ink-log", branch = "master", default-features = false, features = ["ink-log-chain-extensions"] }

bs58 = { version = "0.4", default-features = false, features = ["alloc"] }
light-bitcoin = { git = "https://github.com/patractlabs/light-bitcoin", branch = "features/ink-support", default-features = false, features = ["ink"] }

bridge_stub = { path = "bridge_stub",  default-features = false, features = ["ink-as-dependency"] }
wbtc = { path = "wbtc",  default-features = false, features = ["ink-as-dependency"] }

# Should be removed once bitvecto-rs/bitvec#105 is resolved
funty = "=1.1.0"

[lib]
name = "bridge_example"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info/std",

    "ink_log/std",

    "bs58/std",
    "light-bitcoin/std",

    "bridge_stub/std",
    "wbtc/std",
]
ink-as-dependency = []

[workspace]
members = [
    "bridge_stub",
    "wbtc",
]
