[package]
name = "btc_bridge"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false }
ink_lang = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { version = "3.0.0-rc2", git = "https://github.com/paritytech/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6", default-features = false, features = ["derive"], optional = true }

primitive-types = { version = "0.9.0", default-features = false }

ink_log = { version = "0.1.0", git = "https://github.com/patractlabs/ink-log", branch = "master", default-features = false }
# Only used for dev network
#ink_log = { version = "0.1.0", git = "https://github.com/patractlabs/ink-log", branch = "master", default-features = false, features = ["ink-log-chain-extensions"] }

[dev-dependencies]
hashbrown = "0.9"
hex = { version = "0.4", default-features = false }
rand = "0.8"
light-bitcoin-chain = { version = "0.2.0", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
light-bitcoin-serialization = { version = "0.2.0", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }

[lib]
name = "btc_bridge"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info/std",

    "primitive-types/std",
    "ink_log/std",
]
ink-as-dependency = []
